name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  logger: ^2.6.2
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#  assets:
#    - image/
#  fonts:
#    - family:
#      fonts:
#        - asset: font/
  
  
  
  
  
  
  
  
  
  
